
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author david
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jd_fechadenacimiento = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_usuarioregistro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pf_contraseñaregistro = new javax.swing.JPasswordField();
        tf_nombreregistro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_puesto = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        tf_correo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_empleados = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_empleados = new javax.swing.JTree();
        jButton3 = new javax.swing.JButton();
        dulceria = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cb_catdulce = new javax.swing.JComboBox<>();
        tf_dulce = new javax.swing.JTextField();
        tf_sabor = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_dulces = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_dulces = new javax.swing.JTree();
        jButton4 = new javax.swing.JButton();
        boleteria = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cb_categoria = new javax.swing.JComboBox<>();
        tf_nombrepelis = new javax.swing.JTextField();
        tf_duracion = new javax.swing.JTextField();
        tf_clasificacion = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_pelis = new javax.swing.JList<>();
        jButton7 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_pelis = new javax.swing.JTree();
        aseo = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_aseo = new javax.swing.JTextField();
        tf_descripcionaseo = new javax.swing.JTextField();
        cb_aseo = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_aseo = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jt_aseo = new javax.swing.JTree();
        jButton9 = new javax.swing.JButton();
        modemple = new javax.swing.JPopupMenu();
        jmi_nombre = new javax.swing.JMenuItem();
        jmi_usuario = new javax.swing.JMenuItem();
        jmi_contra = new javax.swing.JMenuItem();
        jmi_correo = new javax.swing.JMenuItem();
        jmi_puesto = new javax.swing.JMenuItem();
        jmi_fecha = new javax.swing.JMenuItem();
        moddulces = new javax.swing.JPopupMenu();
        jmi_nombredulce = new javax.swing.JMenuItem();
        jmi_sabor = new javax.swing.JMenuItem();
        jmi_catdulce = new javax.swing.JMenuItem();
        modpeli = new javax.swing.JPopupMenu();
        modaseo = new javax.swing.JPopupMenu();
        modificar_puesto = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        modificar_fechanaci = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jdc_mod = new com.toedter.calendar.JDateChooser();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_usuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pf_password = new javax.swing.JPasswordField();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("agregar empleados");

        jLabel4.setText("nombre");

        jLabel5.setText("fecha de nacimiento");

        jLabel6.setText("usuario");

        tf_usuarioregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usuarioregistroActionPerformed(evt);
            }
        });

        jLabel7.setText("contraseña");

        jLabel8.setText("correo");

        jLabel9.setText("puesto");

        cb_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dulceria", "boleteria", "aseo" }));

        jButton2.setText("agregar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jd_fechadenacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_usuarioregistro)
                                    .addComponent(tf_nombreregistro))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pf_contraseñaregistro)
                    .addComponent(cb_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_correo, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(pf_contraseñaregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombreregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jd_fechadenacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_usuarioregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cb_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))))
        );

        jl_empleados.setModel(new DefaultListModel());
        jl_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_empleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_empleados);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("empleados");
        jt_empleados.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jt_empleados);

        jButton3.setText("ver por puesto");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout adminLayout = new javax.swing.GroupLayout(admin.getContentPane());
        admin.getContentPane().setLayout(adminLayout);
        adminLayout.setHorizontalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(adminLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(108, 108, 108)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        adminLayout.setVerticalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(adminLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jButton3)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("agregar dulce");

        jLabel11.setText("nombre");

        jLabel12.setText("sabor");

        jLabel13.setText("categoria");

        cb_catdulce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chocolates", "gomitas", "paletas", "chicles" }));

        jButton5.setText("agregar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_catdulce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tf_sabor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(tf_dulce, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5)))))
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_dulce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_sabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cb_catdulce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jl_dulces.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_dulces);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("dulces");
        jt_dulces.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane4.setViewportView(jt_dulces);

        jButton4.setText("ver por categoria");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dulceriaLayout = new javax.swing.GroupLayout(dulceria.getContentPane());
        dulceria.getContentPane().setLayout(dulceriaLayout);
        dulceriaLayout.setHorizontalGroup(
            dulceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dulceriaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        dulceriaLayout.setVerticalGroup(
            dulceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dulceriaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(dulceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dulceriaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dulceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(dulceriaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton4)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("agregar pelicula");

        jLabel15.setText("nombre");

        jLabel16.setText("duracion");

        jLabel17.setText("clasificacion");

        jLabel18.setText("categoria");

        cb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "terror", "comedia", "romance", "drama", "accion", "infantil" }));

        jButton6.setText("agregar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(215, 215, 215))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_nombrepelis)
                    .addComponent(tf_duracion)
                    .addComponent(tf_clasificacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(138, 138, 138))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_nombrepelis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tf_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton6)))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_clasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jl_pelis.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jl_pelis);

        jButton7.setText("ver por categoria");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("peliculas");
        jt_pelis.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane6.setViewportView(jt_pelis);

        javax.swing.GroupLayout boleteriaLayout = new javax.swing.GroupLayout(boleteria.getContentPane());
        boleteria.getContentPane().setLayout(boleteriaLayout);
        boleteriaLayout.setHorizontalGroup(
            boleteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(boleteriaLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButton7)
                .addGap(115, 115, 115)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        boleteriaLayout.setVerticalGroup(
            boleteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boleteriaLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(boleteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boleteriaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(boleteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(boleteriaLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton7)))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("agregar productos de limpieza");

        jLabel20.setText("nombre");

        jLabel21.setText("descripcion");

        jLabel22.setText("funcion");

        cb_aseo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "limpieza de pisos", "limpieza de vidrios", "limpieza de mesas" }));

        jButton8.setText("agregar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_aseo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_aseo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addComponent(tf_descripcionaseo, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(162, 162, 162))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addGap(232, 232, 232))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_aseo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_descripcionaseo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cb_aseo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton8))
        );

        jl_aseo.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(jl_aseo);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("productos de aseo");
        jt_aseo.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane8.setViewportView(jt_aseo);

        jButton9.setText("ver por funcion");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout aseoLayout = new javax.swing.GroupLayout(aseo.getContentPane());
        aseo.getContentPane().setLayout(aseoLayout);
        aseoLayout.setHorizontalGroup(
            aseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(aseoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        aseoLayout.setVerticalGroup(
            aseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aseoLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(aseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aseoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(aseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(aseoLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton9)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jmi_nombre.setText("modificar nombre");
        jmi_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_nombreActionPerformed(evt);
            }
        });
        modemple.add(jmi_nombre);

        jmi_usuario.setText("modificar usuario");
        jmi_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_usuarioActionPerformed(evt);
            }
        });
        modemple.add(jmi_usuario);

        jmi_contra.setText("modificar contraseña");
        jmi_contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_contraActionPerformed(evt);
            }
        });
        modemple.add(jmi_contra);

        jmi_correo.setText("modificar correo");
        jmi_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_correoActionPerformed(evt);
            }
        });
        modemple.add(jmi_correo);

        jmi_puesto.setText("modificar puesto");
        jmi_puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_puestoActionPerformed(evt);
            }
        });
        modemple.add(jmi_puesto);

        jmi_fecha.setText("modificar fecha de nacimiento");
        jmi_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_fechaActionPerformed(evt);
            }
        });
        modemple.add(jmi_fecha);

        jmi_nombredulce.setText("modificar nombre");
        jmi_nombredulce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_nombredulceActionPerformed(evt);
            }
        });
        moddulces.add(jmi_nombredulce);

        jmi_sabor.setText("modificar sabor");
        jmi_sabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_saborActionPerformed(evt);
            }
        });
        moddulces.add(jmi_sabor);

        jmi_catdulce.setText("modificar categoria");
        moddulces.add(jmi_catdulce);

        jLabel23.setText("ingrese puesto");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dulceria", "boleteria", "aseo" }));

        jButton10.setText("guardar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout modificar_puestoLayout = new javax.swing.GroupLayout(modificar_puesto.getContentPane());
        modificar_puesto.getContentPane().setLayout(modificar_puestoLayout);
        modificar_puestoLayout.setHorizontalGroup(
            modificar_puestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificar_puestoLayout.createSequentialGroup()
                .addGroup(modificar_puestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificar_puestoLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(modificar_puestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(modificar_puestoLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton10)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        modificar_puestoLayout.setVerticalGroup(
            modificar_puestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificar_puestoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel23)
                .addGap(29, 29, 29)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addContainerGap())
        );

        jLabel24.setText("ingrese fecha de nacimiento");

        jButton11.setText("guardar");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout modificar_fechanaciLayout = new javax.swing.GroupLayout(modificar_fechanaci.getContentPane());
        modificar_fechanaci.getContentPane().setLayout(modificar_fechanaciLayout);
        modificar_fechanaciLayout.setHorizontalGroup(
            modificar_fechanaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificar_fechanaciLayout.createSequentialGroup()
                .addGroup(modificar_fechanaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificar_fechanaciLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel24))
                    .addGroup(modificar_fechanaciLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jdc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificar_fechanaciLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jButton11)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        modificar_fechanaciLayout.setVerticalGroup(
            modificar_fechanaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificar_fechanaciLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel24)
                .addGap(38, 38, 38)
                .addComponent(jdc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton11)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("usuario");

        jLabel2.setText("contraseña");

        jButton1.setText("log in");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_usuario)
                            .addComponent(pf_password, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_usuarioregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usuarioregistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usuarioregistroActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if ((jt_usuario.getText().equals("admin")) && (pf_password.getText().equals("admin"))) {
            admin.setModal(true);
            admin.pack();
            admin.setLocationRelativeTo(this);
            admin.setVisible(true);
        } else {
            DefaultListModel modelo = (DefaultListModel) jl_empleados.getModel();
            for (int i = 0; i < modelo.getSize(); i++) {
                if ((((empleado) modelo.get(i)).getUsuario().equals(jt_usuario.getText())) && (((empleado) modelo.get(i)).getContraseña().equals(pf_password.getText())) && (((empleado) modelo.get(i)).getPuesto().equals("dulceria"))) {
                    dulceria.setModal(true);
                    dulceria.pack();
                    dulceria.setLocationRelativeTo(this);
                    dulceria.setVisible(true);
                } else if ((((empleado) modelo.get(i)).getUsuario().equals(jt_usuario.getText())) && (((empleado) modelo.get(i)).getContraseña().equals(pf_password.getText())) && (((empleado) modelo.get(i)).getPuesto().equals("boleteria"))) {
                    boleteria.setModal(true);
                    boleteria.pack();
                    boleteria.setLocationRelativeTo(this);
                    boleteria.setVisible(true);
                } else if ((((empleado) modelo.get(i)).getUsuario().equals(jt_usuario.getText())) && (((empleado) modelo.get(i)).getContraseña().equals(pf_password.getText())) && (((empleado) modelo.get(i)).getPuesto().equals("aseo"))) {
                    aseo.setModal(true);
                    aseo.pack();
                    aseo.setLocationRelativeTo(this);
                    aseo.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_empleados.getModel();
        modelo.addElement(new empleado(tf_nombreregistro.getText(), jd_fechadenacimiento.getDate(), tf_usuarioregistro.getText(), pf_contraseñaregistro.getText(), tf_correo.getText(), (String) cb_puesto.getSelectedItem()));
        jl_empleados.setModel(modelo);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_dulces.getModel();
        modelo.addElement(new dulces(tf_dulce.getText(), tf_sabor.getText(), (String) cb_catdulce.getSelectedItem()));
        jl_dulces.setModel(modelo);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_pelis.getModel();
        modelo.addElement(new peliculas(tf_nombrepelis.getText(), tf_duracion.getText(), tf_clasificacion.getText(), (String) cb_categoria.getSelectedItem()));
        jl_pelis.setModel(modelo);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_aseo.getModel();
        modelo.addElement(new implementosaseo(tf_aseo.getText(), tf_descripcionaseo.getText(), (String) cb_aseo.getSelectedItem()));
        jl_aseo.setModel(modelo);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_dulces.getModel();
        for (int i = 0; i < modelo.getSize(); i++) {
            DefaultTreeModel modeloArbol = (DefaultTreeModel) jt_dulces.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
            String sabor, nombre, categoria;
            sabor = ((dulces) modelo.get(i)).getSabor();
            nombre = ((dulces) modelo.get(i)).getNombre();
            categoria = ((dulces) modelo.get(i)).getCategoria();
            int centinela = -1;
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals(categoria)) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new dulces(nombre, sabor, categoria));
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                    centinela = 1;
                }
            }
            if (centinela == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(categoria);
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new dulces(nombre, sabor, categoria));
                n.add(p);
                raiz.add(n);
            }
            modeloArbol.reload();
        }

    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_pelis.getModel();
        for (int i = 0; i < modelo.getSize(); i++) {
            DefaultTreeModel modeloArbol = (DefaultTreeModel) jt_pelis.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
            String nombre, duracion, clasificacion, categoria;
            duracion = ((peliculas) modelo.get(i)).getDuracion();
            nombre = ((peliculas) modelo.get(i)).getNombre();
            categoria = ((peliculas) modelo.get(i)).getCategoria();
            clasificacion = ((peliculas) modelo.get(i)).getClasificacion();
            int centinela = -1;
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals(categoria)) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new peliculas(nombre, duracion, clasificacion, categoria));
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                    centinela = 1;
                }
            }
            if (centinela == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(categoria);
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new peliculas(nombre, duracion, clasificacion, categoria));
                n.add(p);
                raiz.add(n);
            }
            modeloArbol.reload();
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_aseo.getModel();
        for (int i = 0; i < modelo.getSize(); i++) {
            DefaultTreeModel modeloArbol = (DefaultTreeModel) jt_aseo.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
            String nombre, descripcion, funcion;
            descripcion = ((implementosaseo) modelo.get(i)).getDescripcion();
            nombre = ((implementosaseo) modelo.get(i)).getNombre();
            funcion = ((implementosaseo) modelo.get(i)).getFuncion();
            int centinela = -1;
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals(funcion)) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new implementosaseo(nombre, descripcion, funcion));
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                    centinela = 1;
                }
            }
            if (centinela == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(funcion);
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new implementosaseo(nombre, descripcion, funcion));
                n.add(p);
                raiz.add(n);
            }
            modeloArbol.reload();
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_empleados.getModel();
        for (int i = 0; i < modelo.getSize(); i++) {
            DefaultTreeModel modeloArbol = (DefaultTreeModel) jt_empleados.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
            String nombre, usuario, contraseña, correo, puesto;
            Date fechanaci;
            usuario = ((empleado) modelo.get(i)).getUsuario();
            nombre = ((empleado) modelo.get(i)).getNombre();
            contraseña = ((empleado) modelo.get(i)).getContraseña();
            correo = ((empleado) modelo.get(i)).getCorreo();
            puesto = ((empleado) modelo.get(i)).getPuesto();
            fechanaci = ((empleado) modelo.get(i)).getFechanaci();
            int centinela = -1;
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals(puesto)) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new empleado(nombre, fechanaci, usuario, contraseña, correo, puesto));
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                    centinela = 1;
                }
            }
            if (centinela == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(puesto);
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new empleado(nombre, fechanaci, usuario, contraseña, correo, puesto));
                n.add(p);
                raiz.add(n);
            }
            modeloArbol.reload();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jl_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_empleadosMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            if (jl_empleados.getSelectedIndex() >= 0) {

                modemple.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_empleadosMouseClicked

    private void jmi_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_nombreActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_empleados.getModel();
        String nombre = JOptionPane.showInputDialog("ingrese nombre ");
        ((empleado) modelo.get(jl_empleados.getSelectedIndex())).setNombre(nombre);
    }//GEN-LAST:event_jmi_nombreActionPerformed

    private void jmi_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_usuarioActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_empleados.getModel();
        String u = JOptionPane.showInputDialog("ingrese usuario ");
        ((empleado) modelo.get(jl_empleados.getSelectedIndex())).setUsuario(u);
    }//GEN-LAST:event_jmi_usuarioActionPerformed

    private void jmi_contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_contraActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_empleados.getModel();
        String c = JOptionPane.showInputDialog("ingrese nueva contra ");
        ((empleado) modelo.get(jl_empleados.getSelectedIndex())).setContraseña(c);
    }//GEN-LAST:event_jmi_contraActionPerformed

    private void jmi_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_correoActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_empleados.getModel();
        String co = JOptionPane.showInputDialog("ingrese correo ");
        ((empleado) modelo.get(jl_empleados.getSelectedIndex())).setCorreo(co);
    }//GEN-LAST:event_jmi_correoActionPerformed

    private void jmi_puestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_puestoActionPerformed
        // TODO add your handling code here:
        modificar_puesto.setModal(true);
        modificar_puesto.pack();
        modificar_puesto.setLocationRelativeTo(this);
        modificar_puesto.setVisible(true);

    }//GEN-LAST:event_jmi_puestoActionPerformed

    private void jmi_nombredulceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_nombredulceActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_dulces.getModel();
        String nombre = JOptionPane.showInputDialog("ingrese nombre ");
        ((dulces) modelo.get(jl_dulces.getSelectedIndex())).setNombre(nombre);
    }//GEN-LAST:event_jmi_nombredulceActionPerformed

    private void jmi_saborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_saborActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_dulces.getModel();
        String sabor = JOptionPane.showInputDialog("ingrese sabor ");
        ((dulces) modelo.get(jl_dulces.getSelectedIndex())).setSabor(sabor);
    }//GEN-LAST:event_jmi_saborActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_empleados.getModel();
        String puesto = JOptionPane.showInputDialog("ingrese puesto ");
        ((empleado) modelo.get(jl_empleados.getSelectedIndex())).setPuesto(puesto);
        modificar_puesto.setVisible(false);
    }//GEN-LAST:event_jButton10MouseClicked

    private void jmi_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_fechaActionPerformed
        // TODO add your handling code here:
        modificar_fechanaci.setModal(true);
        modificar_fechanaci.pack();
        modificar_fechanaci.setLocationRelativeTo(this);
        modificar_fechanaci.setVisible(true);
    }//GEN-LAST:event_jmi_fechaActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        Date nueva=jdc_mod.getDate();
        DefaultListModel modelo = (DefaultListModel) jl_empleados.getModel();
        ((empleado) modelo.get(jl_empleados.getSelectedIndex())).setFechanaci(nueva);
        modificar_fechanaci.setVisible(false);
    }//GEN-LAST:event_jButton11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog admin;
    private javax.swing.JDialog aseo;
    private javax.swing.JDialog boleteria;
    private javax.swing.JComboBox<String> cb_aseo;
    private javax.swing.JComboBox<String> cb_catdulce;
    private javax.swing.JComboBox<String> cb_categoria;
    private javax.swing.JComboBox<String> cb_puesto;
    private javax.swing.JDialog dulceria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private com.toedter.calendar.JDateChooser jd_fechadenacimiento;
    private com.toedter.calendar.JDateChooser jdc_mod;
    private javax.swing.JList<String> jl_aseo;
    private javax.swing.JList<String> jl_dulces;
    private javax.swing.JList<String> jl_empleados;
    private javax.swing.JList<String> jl_pelis;
    private javax.swing.JMenuItem jmi_catdulce;
    private javax.swing.JMenuItem jmi_contra;
    private javax.swing.JMenuItem jmi_correo;
    private javax.swing.JMenuItem jmi_fecha;
    private javax.swing.JMenuItem jmi_nombre;
    private javax.swing.JMenuItem jmi_nombredulce;
    private javax.swing.JMenuItem jmi_puesto;
    private javax.swing.JMenuItem jmi_sabor;
    private javax.swing.JMenuItem jmi_usuario;
    private javax.swing.JTree jt_aseo;
    private javax.swing.JTree jt_dulces;
    private javax.swing.JTree jt_empleados;
    private javax.swing.JTree jt_pelis;
    private javax.swing.JTextField jt_usuario;
    private javax.swing.JPopupMenu modaseo;
    private javax.swing.JPopupMenu moddulces;
    private javax.swing.JPopupMenu modemple;
    private javax.swing.JDialog modificar_fechanaci;
    private javax.swing.JDialog modificar_puesto;
    private javax.swing.JPopupMenu modpeli;
    private javax.swing.JPasswordField pf_contraseñaregistro;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tf_aseo;
    private javax.swing.JTextField tf_clasificacion;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_descripcionaseo;
    private javax.swing.JTextField tf_dulce;
    private javax.swing.JTextField tf_duracion;
    private javax.swing.JTextField tf_nombrepelis;
    private javax.swing.JTextField tf_nombreregistro;
    private javax.swing.JTextField tf_sabor;
    private javax.swing.JTextField tf_usuarioregistro;
    // End of variables declaration//GEN-END:variables

    String usuario = "admin";
    String contraseña = "admin";
}
